# Generated by Django 3.1 on 2020-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='Ingredience'),
        ),
        migrations.AlterField(
            model_name='food',
            name='link',
            field=models.TextField(default='link na recept'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(default='Jmeno jidla'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default='Cena jidla'),
        ),
        migrations.AlterField(
            model_name='food',
            name='u_ingredients',
            field=models.TextField(default='Nenalezene polozky'),
        ),
    ]
